import { jsx as _jsx } from "react/jsx-runtime";
import { Buffer } from "buffer";
window.Buffer = Buffer;
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import { ConnectionProvider, WalletProvider, } from "@solana/wallet-adapter-react";
import { WalletModalProvider, } from "@solana/wallet-adapter-react-ui";
import { PhantomWalletAdapter } from "@solana/wallet-adapter-wallets";
import "@solana/wallet-adapter-react-ui/styles.css";
const wallets = [new PhantomWalletAdapter()];
ReactDOM.createRoot(document.getElementById("root")).render(_jsx(ConnectionProvider, { endpoint: "https://api.mainnet-beta.solana.com", children: _jsx(WalletProvider, { wallets: wallets, autoConnect: true, children: _jsx(WalletModalProvider, { children: _jsx(App, {}) }) }) }));
